### ISSUE TITLE
Pretty comprehensive methodology summary in rare disease

### ISSUE THREAD

**Issue by allaway** [jaybee84/ml-in-rd#27]
How do we differentiate the current perspective piece from this paper? 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6947640/
Includes MultiPLIER!

**Comment by jaybee84** [comment]
This is a really interesting paper.. and quite unique in that it has a methods section even though it is a literature review, where they outline the selection and exclusion criteria of the papers they reviewed! 

I do see a couple of ways our work can be differentiated from this:
1. Our main focus is on the algorithms, why some methodologies can be applied to rare diseases, and what are some of the caveats of the methods to keep in mind for proper interpretation
2. We will also focus mainly on disease interpretation/classification rather than clinical diagnostics and precision medicine

Lastly, it seems that the target audience for the two papers may be different. Our target audience is ideally someone who is trying to pick a methodology to apply to their own rare disease data for interpretation, or evaluate the veracity of interpretations from ML applications to RD data in a paper; while the audience for this review seems to be the general research community (who may not be applying the algorithms themselves).

What do you all think?
