### ISSUE TITLE
master --> main?

### ISSUE THREAD

**Issue by allaway** [jaybee84/ml-in-rd#62]
This is a small change, but I am wondering if this will break manubot to switch?

**Comment by jaybee84** [comment]
it will probably break the html/pdf output build.. but that can be fixed from the config file I think...

wondering what else might break :)

**Comment by cgreene** [comment]
Let's raise this as an issue upstream. They should also address it.

**Comment by allaway** [comment]
Good point. Happy to do this!

**Comment by allaway** [comment]
Oops, I see that @jaybee84 already did. Thanks!

**Comment by jaybee84** [comment]
Master has been changed to "main". Manubot.yaml has been configured to deploy manuscript build from "main" in addition to "draft-branch".

Since our default branch is "draft-branch" the change from master to main should not break anything in our daily PRs. 

Please let me know if anything is broken for any of you. :)

**Comment by jaclyn-taroni** [comment]
Thanks @jaybee84!

**Comment by allaway** [comment]
Thanks!
